declare type Icons = 'check'
    | 'text-t'
    | 'caret-down'
    | 'paint-brush'
    | 'x'
    | 'at'
    | 'columns'
    | 'split-horizontal'
    | 'frame-corners'
    | 'arrows-out-simple'
    | 'arrows-out'
    | 'arrows-in'
    | 'corners-out'